const BOARD_SIZE = 720;
const SQUARE_SIZE = BOARD_SIZE / 8.0;

const LIGHT_SQUARE_COLOR = '#FFFFDD';
const DARK_SQUARE_COLOR = '#86A666';
const HIGHLIGHTED_LIGHT_SQUARE_COLOR = '#89A97D';
const HIGHLIGHTED_DARK_SQUARE_COLOR = '#4C7D42';

// const START_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const START_FEN = 'rnbqkbnr/8/8/8/8/8/8/RNBQKBNR w KQkq - 0 1';
